import type {
  ActivityLog,
  Alert,
  Client,
  ClientComplianceOfficer,
  ComplianceManual,
  Expediente,
  ExpedienteStage,
  KycRecord,
  PldOperation,
  Profile,
  TrainingSession,
  UnusualNotice,
} from './types'

const now = new Date().toISOString()

export const DEMO_PROFILE: Profile = {
  id: 'demo-user-1',
  full_name: 'Lic. Adrián Gerardo',
  email: 'juridicofiscaleg@gmail.com',
  role: 'admin',
  created_at: now,
}

export const DEMO_CLIENTS: Client[] = [
  {
    id: 'client-1',
    name: 'Grupo Financiero del Norte SA de CV',
    client_type: 'persona_moral',
    rfc: 'GFN850101ABC',
    email: 'contacto@grupofinanciero.mx',
    phone: '662 304 6770',
    industry: 'Servicios financieros',
    vulnerable_activity: true,
    nationality: 'México',
    risk_level: 'alto',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'client-2',
    name: 'María Elena Rodríguez Pérez',
    client_type: 'persona_fisica',
    rfc: 'ROPM780512XYZ',
    email: 'maria.rodriguez@email.com',
    phone: '662 123 4567',
    industry: 'Comercio',
    vulnerable_activity: true,
    nationality: 'México',
    risk_level: 'medio',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'client-3',
    name: 'Constructora Pacífico SA de CV',
    client_type: 'persona_moral',
    rfc: 'CPA920301DEF',
    email: 'legal@constructorapacifico.mx',
    phone: '662 987 6543',
    industry: 'Construcción',
    risk_level: 'bajo',
    created_at: now,
    updated_at: now,
  },
]

export const DEMO_EXPEDIENTES: Expediente[] = [
  {
    id: 'exp-1',
    client_id: 'client-1',
    title: 'Implementación programa PLD/FT 2026',
    matter_type: 'pld',
    description: 'Diseño e implementación del programa de cumplimiento PLD conforme a la LFPIORPI.',
    status: 'activo',
    current_stage_index: 2,
    priority: 'alta',
    assigned_to: 'demo-user-1',
    opened_at: now,
    updated_at: now,
    clients: DEMO_CLIENTS[0],
  },
  {
    id: 'exp-2',
    client_id: 'client-2',
    title: 'Debida diligencia — apertura cuenta',
    matter_type: 'kyc',
    description: 'KYC completo para nuevo cliente persona física con actividad vulnerable.',
    status: 'activo',
    current_stage_index: 1,
    priority: 'urgente',
    assigned_to: 'demo-user-1',
    opened_at: now,
    updated_at: now,
    clients: DEMO_CLIENTS[1],
  },
  {
    id: 'exp-3',
    client_id: 'client-3',
    title: 'Diagnóstico de cumplimiento PLD',
    matter_type: 'diagnostico_pld',
    description: 'Evaluación inicial del nivel de cumplimiento normativo.',
    status: 'activo',
    current_stage_index: 0,
    priority: 'media',
    opened_at: now,
    updated_at: now,
    clients: DEMO_CLIENTS[2],
  },
]

export const DEMO_STAGES: Record<string, ExpedienteStage[]> = {
  'exp-1': [
    { id: 's1-0', expediente_id: 'exp-1', stage_index: 0, name: 'Diagnóstico inicial', status: 'completada', completed_at: now },
    { id: 's1-1', expediente_id: 'exp-1', stage_index: 1, name: 'Análisis de riesgo', status: 'completada', completed_at: now },
    { id: 's1-2', expediente_id: 'exp-1', stage_index: 2, name: 'Matriz de riesgo', status: 'en_progreso', started_at: now },
    { id: 's1-3', expediente_id: 'exp-1', stage_index: 3, name: 'Plan de acción', status: 'pendiente' },
    { id: 's1-4', expediente_id: 'exp-1', stage_index: 4, name: 'Capacitación', status: 'pendiente' },
    { id: 's1-5', expediente_id: 'exp-1', stage_index: 5, name: 'Implementación', status: 'pendiente' },
    { id: 's1-6', expediente_id: 'exp-1', stage_index: 6, name: 'Seguimiento', status: 'pendiente' },
  ],
  'exp-2': [
    { id: 's2-0', expediente_id: 'exp-2', stage_index: 0, name: 'Solicitud de documentos', status: 'completada', completed_at: now },
    { id: 's2-1', expediente_id: 'exp-2', stage_index: 1, name: 'Revisión inicial', status: 'en_progreso', started_at: now },
    { id: 's2-2', expediente_id: 'exp-2', stage_index: 2, name: 'Debida diligencia', status: 'pendiente' },
    { id: 's2-3', expediente_id: 'exp-2', stage_index: 3, name: 'Análisis de riesgo', status: 'pendiente' },
    { id: 's2-4', expediente_id: 'exp-2', stage_index: 4, name: 'Aprobación', status: 'pendiente' },
    { id: 's2-5', expediente_id: 'exp-2', stage_index: 5, name: 'Monitoreo', status: 'pendiente' },
  ],
  'exp-3': [
    { id: 's3-0', expediente_id: 'exp-3', stage_index: 0, name: 'Levantamiento', status: 'en_progreso', started_at: now },
    { id: 's3-1', expediente_id: 'exp-3', stage_index: 1, name: 'Gap analysis', status: 'pendiente' },
    { id: 's3-2', expediente_id: 'exp-3', stage_index: 2, name: 'Reporte de hallazgos', status: 'pendiente' },
    { id: 's3-3', expediente_id: 'exp-3', stage_index: 3, name: 'Presentación', status: 'pendiente' },
    { id: 's3-4', expediente_id: 'exp-3', stage_index: 4, name: 'Cierre', status: 'pendiente' },
  ],
}

export const DEMO_KYC: KycRecord[] = [
  {
    id: 'kyc-1',
    client_id: 'client-2',
    expediente_id: 'exp-2',
    status: 'en_revision',
    risk_score: 45,
    checklist: {
      identificacion: true,
      comprobante_domicilio: true,
      constancia_fiscal: true,
      declaracion_origen_recursos: false,
      lista_negra_verificada: false,
    },
    pep: false,
    sanctions_check: true,
    created_at: now,
    updated_at: now,
    clients: DEMO_CLIENTS[1],
  },
  {
    id: 'kyc-2',
    client_id: 'client-1',
    status: 'aprobado',
    risk_score: 72,
    checklist: {
      identificacion: true,
      acta_constitutiva: true,
      beneficiario_controlador: true,
      constancia_fiscal: true,
      lista_negra_verificada: true,
    },
    pep: false,
    sanctions_check: true,
    expires_at: '2027-01-15',
    created_at: now,
    updated_at: now,
    clients: DEMO_CLIENTS[0],
  },
]

export const DEMO_OPERATIONS: PldOperation[] = [
  {
    id: 'op-1',
    client_id: 'client-1',
    expediente_id: 'exp-1',
    operation_date: '2026-07-10',
    operation_type: 'compra_venta_inmueble',
    amount: 8500000,
    currency: 'MXN',
    description: 'Compraventa de inmueble comercial — zona industrial',
    unusual: true,
    reported: false,
    created_by: 'demo-user-1',
    created_at: now,
    updated_at: now,
    clients: DEMO_CLIENTS[0],
  },
  {
    id: 'op-2',
    client_id: 'client-2',
    operation_date: '2026-06-15',
    operation_type: 'desarrollo_inmobiliario',
    amount: 1200000,
    currency: 'MXN',
    description: 'Anticipo desarrollo habitacional',
    unusual: false,
    reported: false,
    created_by: 'demo-user-1',
    created_at: now,
    updated_at: now,
    clients: DEMO_CLIENTS[1],
  },
]

export const DEMO_NOTICES: UnusualNotice[] = [
  {
    id: 'notice-1',
    client_id: 'client-1',
    operation_id: 'op-1',
    notice_type: '24h',
    status: 'borrador',
    title: 'Operación inusual — compraventa inmueble',
    narrative: 'Operación por monto superior al umbral de actividad vulnerable. Cliente con riesgo alto.',
    amount: 8500000,
    detected_at: '2026-07-10',
    created_by: 'demo-user-1',
    assigned_to: 'demo-user-1',
    created_at: now,
    updated_at: now,
    clients: DEMO_CLIENTS[0],
  },
]

export const DEMO_MANUALS: ComplianceManual[] = [
  {
    id: 'manual-1',
    client_id: 'client-1',
    title: 'Manual PLD/FT',
    version: '2.1',
    file_name: 'manual-pld-gfn-2026.pdf',
    effective_date: '2026-01-01',
    is_active: true,
    created_at: now,
    updated_at: now,
    clients: DEMO_CLIENTS[0],
  },
]

export const DEMO_OFFICERS: ClientComplianceOfficer[] = [
  {
    id: 'off-1',
    client_id: 'client-1',
    name: 'Lic. Roberto Mendoza',
    email: 'roberto.mendoza@grupofinanciero.mx',
    phone: '662 304 6771',
    rfc: 'MER850101ABC',
    appointed_at: '2025-01-15',
    is_active: true,
    created_at: now,
    updated_at: now,
    clients: DEMO_CLIENTS[0],
  },
  {
    id: 'off-2',
    client_id: 'client-2',
    name: 'Lic. Ana Lucía Vega',
    email: 'ana.vega@email.com',
    appointed_at: '2026-03-01',
    is_active: true,
    created_at: now,
    updated_at: now,
    clients: DEMO_CLIENTS[1],
  },
]

export const DEMO_TRAININGS: TrainingSession[] = [
  {
    id: 'train-1',
    client_id: 'client-1',
    officer_id: 'off-1',
    title: 'Capacitación anual PLD/FT 2026',
    session_date: '2026-06-20',
    topic: 'LFPIORPI, señales de alerta y avisos',
    participants: 'Lic. Adrián Gerardo\nLic. María Pérez',
    duration_hours: 4,
    instructor: 'Lic. Adrián Gerardo',
    location: 'Sala de juntas',
    modality: 'presencial',
    notes: 'Repaso de umbrales, KYC y procedimiento de avisos inusuales.',
    created_by: 'demo-user-1',
    created_at: now,
    clients: DEMO_CLIENTS[0],
    officers: DEMO_OFFICERS[0],
  },
]

export const DEMO_ALERTS: Alert[] = [
  {
    id: 'alert-1',
    expediente_id: 'exp-2',
    client_id: 'client-2',
    title: 'Documentos KYC pendientes',
    message: 'Falta declaración de origen de recursos y verificación de listas negras.',
    alert_type: 'kyc',
    due_date: '2026-07-20',
    resolved: false,
    created_at: now,
    clients: DEMO_CLIENTS[1],
    expedientes: DEMO_EXPEDIENTES[1],
  },
  {
    id: 'alert-2',
    expediente_id: 'exp-1',
    client_id: 'client-1',
    title: 'Entrega matriz de riesgo',
    message: 'Fecha límite para entrega de matriz de riesgo al comité.',
    alert_type: 'vencimiento',
    due_date: '2026-07-25',
    resolved: false,
    created_at: now,
    clients: DEMO_CLIENTS[0],
    expedientes: DEMO_EXPEDIENTES[0],
  },
]

export const DEMO_ACTIVITY: ActivityLog[] = [
  {
    id: 'act-1',
    expediente_id: 'exp-1',
    client_id: 'client-1',
    user_id: 'demo-user-1',
    action: 'etapa_completada',
    description: 'Completó etapa "Análisis de riesgo"',
    created_at: now,
    profiles: DEMO_PROFILE,
  },
  {
    id: 'act-2',
    expediente_id: 'exp-2',
    client_id: 'client-2',
    user_id: 'demo-user-1',
    action: 'documento_subido',
    description: 'Subió identificación oficial del cliente',
    created_at: now,
    profiles: DEMO_PROFILE,
  },
  {
    id: 'act-3',
    expediente_id: 'exp-3',
    client_id: 'client-3',
    user_id: 'demo-user-1',
    action: 'expediente_creado',
    description: 'Creó expediente "Diagnóstico de cumplimiento PLD"',
    created_at: now,
    profiles: DEMO_PROFILE,
  },
]
